using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using Slide2Doc.Application.Interfaces;
using Slide2Doc.Application.Models;
using Slide2Doc.Domain.Entities;

namespace Slide2Doc.Infrastructure.Composers;

public class OpenXmlDocxComposer : IDocxComposer
{
    public Task<Stream> ComposeAsync(IReadOnlyList<TopicMatch> matches, IReadOnlyList<SourceDocument> sources, CompileOptions options, CancellationToken cancellationToken)
    {
        var output = new MemoryStream();
        using var document = WordprocessingDocument.Create(output, WordprocessingDocumentType.Document, autoSave: true);
        var mainPart = document.AddMainDocumentPart();
        mainPart.Document = new Document(new Body());

        var body = mainPart.Document.Body!;

        foreach (var match in matches.OrderBy(m => m.Topic.Order))
        {
            cancellationToken.ThrowIfCancellationRequested();
            AddHeadingParagraph(body, match.Topic.Title);

            if (match.Section != null)
            {
                var source = sources.FirstOrDefault(s => string.Equals(s.Name, match.Section.SourceDocName, StringComparison.OrdinalIgnoreCase));
                if (source == null)
                {
                    continue;
                }

                using var sourceDoc = WordprocessingDocument.Open(source.OpenRead(), false);
                var sourceBody = sourceDoc.MainDocumentPart?.Document?.Body;
                if (sourceBody == null)
                {
                    continue;
                }

                var elements = sourceBody.Elements<OpenXmlElement>().ToList();
                var start = Math.Max(0, match.Section.StartIndex);
                var end = Math.Min(elements.Count - 1, match.Section.EndIndex);
                for (int i = start; i <= end; i++)
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    body.Append(elements[i].CloneNode(true));
                }
            }
        }

        body.AppendChild(new Paragraph(new Run(new Text("Generated by Slide2Doc"))));
        if (options.IncludeToc)
        {
            body.InsertAt(new Paragraph(new Run(new Text("Table of Contents (not implemented in MVP)"))), 0);
        }

        body.Save();
        output.Position = 0;
        return Task.FromResult<Stream>(output);
    }

    private static void AddHeadingParagraph(Body body, string text)
    {
        var paragraph = new Paragraph(
            new ParagraphProperties(new ParagraphStyleId { Val = "Heading1" }),
            new Run(new Text(text)));
        body.Append(paragraph);
    }
}
